# GitHub Pages Jekyll配置
title: "服务器优化工具集合"
description: "一键安装Linux服务器性能优化工具"
url: "https://ss.hide.ss"
baseurl: ""

# 禁用Jekyll处理某些文件
include:
  - install-online.sh
  - bootstrap.sh
  - version.txt

# 插件配置
plugins:
  - jekyll-sitemap

# 构建设置
markdown: kramdown
highlighter: rouge

# 排除不需要的文件
exclude:
  - README.md
  # - DEPLOY.md  # 已删除
  - .github/
  - .git/
  - .gitignore